# -*- coding: utf-8 -*-
"""Generate long mock postDetails for missing feed ids and inject into HomeModel.ets"""
from pathlib import Path


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def reply(rid, name, content, time, region, reply_to="", is_author=False):
    return f"""          {{
            id: '{rid}',
            authorName: '{esc(name)}',
            isAuthor: {'true' if is_author else 'false'},
            content: '{esc(content)}',
            timeText: '{esc(time)}',
            region: '{esc(region)}',
            replyToName: '{esc(reply_to)}',
          }}"""


def comment(
    cid,
    name,
    color,
    text,
    level,
    content,
    time,
    region,
    likes,
    replies,
    pinned=False,
    is_author=False,
    is_official=False,
    image_key="",
    image_color="",
):
    rep = ",\n".join(replies) if replies else ""
    rep_block = f"\n{rep}\n        " if replies else ""
    reply_total = len(replies) + (2 if len(replies) >= 2 else 0)
    return f"""      {{
        id: '{cid}',
        authorName: '{esc(name)}',
        authorAvatarColor: '{color}',
        authorAvatarText: '{esc(text)}',
        levelLabel: '{esc(level)}',
        isAuthor: {'true' if is_author else 'false'},
        isOfficial: {'true' if is_official else 'false'},
        isPinned: {'true' if pinned else 'false'},
        timeText: '{esc(time)}',
        region: '{esc(region)}',
        content: '{esc(content)}',
        imageKey: '{esc(image_key)}',
        imageColor: '{esc(image_color)}',
        likeCount: {likes},
        replyTotal: {reply_total},
        replies: [{rep_block}],
      }}"""


def body(lines):
    return ",\n".join(f"      '{esc(x)}'" for x in lines)


def tags(arr):
    return ", ".join(f"'{esc(t)}'" for t in arr)


def detail(d):
    comments = ",\n".join(d["comments"])
    return f"""  {{
    id: '{d['id']}',
    fullTitle: '{esc(d['fullTitle'])}',
    authorName: '{esc(d['authorName'])}',
    authorAvatarColor: '{d['authorAvatarColor']}',
    authorAvatarText: '{esc(d['authorAvatarText'])}',
    levelLabel: '{esc(d['levelLabel'])}',
    isOfficial: {'true' if d['isOfficial'] else 'false'},
    isFollowing: {'true' if d['isFollowing'] else 'false'},
    publishTime: '{esc(d['publishTime'])}',
    region: '{esc(d['region'])}',
    circles: [{tags(d['circles'])}],
    hotTag: '{esc(d.get('hotTag', ''))}',
    heroMediaKey: '{esc(d['heroMediaKey'])}',
    heroColor: '{d['heroColor']}',
    caption: '{esc(d['caption'])}',
    bodyParagraphs: [
{body(d['body'])}
    ],
    relatedLink: '{esc(d.get('relatedLink', ''))}',
    authorNote: '{esc(d.get('authorNote', ''))}',
    topicTags: [{tags(d['topicTags'])}],
    relatedSearch: '{esc(d.get('relatedSearch', ''))}',
    collectionName: '{esc(d.get('collectionName', ''))}',
    collectionProgress: '{esc(d.get('collectionProgress', ''))}',
    likeCount: {d['likeCount']},
    starCount: {d['starCount']},
    awardCount: {d['awardCount']},
    commentCount: {d['commentCount']},
    comments: [
{comments}
    ],
  }}"""


def build_posts():
    posts = []

    posts.append(
        dict(
            id="r4",
            fullTitle="潜水员戴夫：刷完图鉴后的毕业装分享",
            authorName="深海打工人",
            authorAvatarColor="#4EC6E8",
            authorAvatarText="海",
            levelLabel="Lv.8",
            isOfficial=False,
            isFollowing=False,
            publishTime="前天20:16",
            region="福建",
            circles=["潜水员戴夫", "PC游戏"],
            hotTag="",
            heroMediaKey="Palworld",
            heroColor="#4EC6E8",
            caption="肝了三周终于集齐图鉴，整理了一套当前版本比较稳的毕业装备路线，适合还在卡关的盒友。",
            body=[
                "先说结论：毕业装不是最贵那套，而是「能覆盖 90% 场景 + 容错高」的那套。我自己是标准肝帝路线——白天刷资源，晚上清图鉴，第三周才把最后几个隐藏物种补齐。",
                "武器方面我最终定在：主手偏输出的中距离枪械，副手带一个稳定的近战保命。很多人一上来就冲最高伤，结果后期精英战翻车。我试过把词条优先级改成：暴击率 > 弹匣/续航 > 纯伤害，打起来会舒服很多。",
                "防具推荐「均衡三件 + 特化两件」。均衡负责减伤和机动，特化看你是缺氧气续航还是缺背包。背包空间真的比想象中重要，尤其是刷图鉴阶段，捡漏材料经常爆仓。",
                "资源循环我是这样做的：每天固定路线清一遍可刷新点，多余材料分解，稀有材料只在活动周集中换。别看到限时就上头全换皮肤，皮肤好看但打不过怪也没用。",
                "图鉴最后卡的几个基本都在夜间地图和深渊区。建议组队或看攻略点位，单人硬刷会心态爆炸。我卡最后一个的时候连续两天只刷到重复，第三天换了路线就出了。",
                "如果是萌新：先别盯着毕业装，把图鉴到 70% 再考虑成型。装备是跟着理解力一起涨的。有问题评论区问，我看到会回。",
            ],
            relatedLink="潜水员戴夫 图鉴清单（社区整理）",
            authorNote="装备会随版本微调，本文基于当前赛季。觉得有用点个赞，我好更新下一期「性价比过渡装」。",
            topicTags=["潜水员戴夫", "毕业装", "图鉴", "攻略"],
            relatedSearch="潜水员戴夫 毕业 装备",
            collectionName="合集【戴夫肝帝笔记】",
            collectionProgress="3/12",
            likeCount=156,
            starCount=48,
            awardCount=6,
            commentCount=41,
            comments=[
                comment(
                    "r4c1",
                    "深海打工人",
                    "#4EC6E8",
                    "海",
                    "Lv.8",
                    "置顶：装备截图在第二张和第三张，词条我用红圈标了。",
                    "前天20:20",
                    "福建",
                    22,
                    [
                        reply("r4c1r1", "戴夫萌新01", "收藏了，周末照着刷", "前天21:02", "浙江"),
                        reply(
                            "r4c1r2",
                            "氧气不足",
                            "背包那条太真实了，我总是爆仓",
                            "前天21:40",
                            "广东",
                            "深海打工人",
                        ),
                    ],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "r4c2",
                    "蓝洞观察员",
                    "#2A8BB0",
                    "蓝",
                    "Lv.14",
                    "主手你用的是哪把？我感觉同档枪手感差挺多。",
                    "昨天10:12",
                    "上海",
                    18,
                    [
                        reply(
                            "r4c2r1",
                            "深海打工人",
                            "中距离那把，偏稳定射速，不吃太极限走位",
                            "昨天11:05",
                            "福建",
                            "蓝洞观察员",
                            True,
                        )
                    ],
                ),
                comment(
                    "r4c3",
                    "肝帝退休",
                    "#6B7CFF",
                    "肝",
                    "Lv.9",
                    "图鉴我卡在深渊那只，路线有推荐吗？",
                    "昨天15:33",
                    "四川",
                    11,
                    [
                        reply(
                            "r4c3r1",
                            "深海打工人",
                            "走右侧岔路，夜间刷新概率高一点，带照明",
                            "昨天16:01",
                            "福建",
                            "肝帝退休",
                            True,
                        ),
                        reply("r4c3r2", "路过盒友", "同问同问，求坐标图", "昨天16:20", "江苏"),
                    ],
                ),
                comment(
                    "r4c4",
                    "咸鱼一天",
                    "#888888",
                    "咸",
                    "Lv.5",
                    "直接抄作业，先点赞再看",
                    "昨天19:48",
                    "湖北",
                    7,
                    [],
                ),
                comment(
                    "r4c5",
                    "词条玄学",
                    "#C9A227",
                    "词",
                    "Lv.11",
                    "暴击率优先这个思路对，我之前纯堆伤害输出环境反而差",
                    "今天09:10",
                    "北京",
                    15,
                    [
                        reply(
                            "r4c5r1",
                            "深海打工人",
                            "对，伤害溢出不如命中和续航",
                            "今天09:40",
                            "福建",
                            "词条玄学",
                            True,
                        )
                    ],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="r5",
            fullTitle="本周 Steam 史低合集：这几款别再犹豫了",
            authorName="史低雷达",
            authorAvatarColor="#1B2838",
            authorAvatarText="S",
            levelLabel="Lv.20",
            isOfficial=True,
            isFollowing=False,
            publishTime="今天08:30",
            region="上海",
            circles=["Steam", "PC游戏"],
            hotTag="",
            heroMediaKey="chain",
            heroColor="#1B2838",
            caption="整理本周值得入手的史低与新史低，含动作、策略、独立游戏。价格仅供参考，下单前再核对一次。",
            body=[
                "又到了一周一度的「钱包保卫战」。本周大促叠加发行商活动，几款长青作品摸到了年内好看的价位。下面按品类拆，每款附一句适不适合入手的判断。",
                "动作向：有一款开放世界动作这两年口碑回暖，史低后性价比明显。如果你本来就在愿望单里躺了半年以上，这周可以动。注意 DLC 是否捆绑，捆绑通常更划算，但只要本体的也可以等等单买。",
                "策略/模拟：一款城市建设+经营的独立作新史低，适合喜欢「再来一回合」的盒友。上手曲线中等，别指望十分钟开局，但沉浸感在线。笔记本核显也能跑，对硬件友好。",
                "独立游戏彩蛋区：两款叙事向短篇都很适合周末清空。一款偏解谜温馨，一款偏反转致郁，二选一就看你心情。体量都在 4–8 小时，史低价属于「喝两杯奶茶」级别。",
                "不建议冲动的：刚发售还在好评发酵期、差评里性能问题集中的那几款，再观察两周。史低是优惠，不是逃命。",
                "购买小技巧：愿望单开「优惠通知」；区域价格差异大的注意账户风险；家庭共享能解决「买了不玩」的一部分焦虑。你有想确认的游戏，评论区甩名，我帮你看是不是真史低。",
            ],
            relatedLink="SteamDB 价格追踪（自行查阅）",
            authorNote="数据整理自公开页面，存在延迟。下单前以 Steam 客户端为准。",
            topicTags=["Steam", "史低", "促销", "愿望单"],
            relatedSearch="Steam 史低 本周",
            collectionName="合集【史低雷达周报】",
            collectionProgress="26/120",
            likeCount=420,
            starCount=166,
            awardCount=21,
            commentCount=128,
            comments=[
                comment(
                    "r5c1",
                    "史低雷达",
                    "#1B2838",
                    "S",
                    "Lv.20",
                    "置顶：评论区抽 3 位送「愿望单代看」服务，说说你最想买但一直没下手的。",
                    "今天08:35",
                    "上海",
                    56,
                    [
                        reply("r5c1r1", "钱包空空", "那款开放世界我蹲了八个月，冲了", "今天09:02", "广东"),
                        reply("r5c1r2", "独立爱好者", "叙事短篇求具体名字私信我！", "今天09:18", "浙江"),
                    ],
                    pinned=True,
                    is_author=True,
                    is_official=True,
                ),
                comment(
                    "r5c2",
                    "愿望单管理员",
                    "#5B8DEF",
                    "愿",
                    "Lv.13",
                    "策略那款我玩了 120 小时，史低值得，别买错 bundle",
                    "今天10:05",
                    "北京",
                    33,
                    [
                        reply(
                            "r5c2r1",
                            "史低雷达",
                            "对，bundle 页要看包含哪些 DLC",
                            "今天10:22",
                            "上海",
                            "愿望单管理员",
                            True,
                        )
                    ],
                ),
                comment(
                    "r5c3",
                    "等等党胜利",
                    "#2F9B63",
                    "等",
                    "Lv.10",
                    "终于轮到我愿望单第一了，感谢雷达",
                    "今天11:40",
                    "四川",
                    19,
                    [],
                ),
                comment(
                    "r5c4",
                    "冲动消费",
                    "#FF5A5A",
                    "冲",
                    "Lv.7",
                    "看完又买了三款，你要赔我",
                    "今天12:15",
                    "江苏",
                    12,
                    [
                        reply(
                            "r5c4r1",
                            "史低雷达",
                            "雷达只负责发光，不负责刹车（笑）",
                            "今天12:30",
                            "上海",
                            "冲动消费",
                            True,
                        )
                    ],
                ),
                comment(
                    "r5c5",
                    "笔记本玩家",
                    "#888888",
                    "本",
                    "Lv.8",
                    "核显能跑的独立作多推几个呗",
                    "今天13:50",
                    "湖南",
                    8,
                    [
                        reply(
                            "r5c5r1",
                            "史低雷达",
                            "下期单独出一期轻配推荐",
                            "今天14:10",
                            "上海",
                            "笔记本玩家",
                            True,
                        )
                    ],
                ),
                comment(
                    "r5c6",
                    "区域党",
                    "#C9A227",
                    "区",
                    "Lv.15",
                    "提醒一下改区风险，别为了几块钱翻车",
                    "今天15:00",
                    "海外",
                    27,
                    [],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="r6",
            fullTitle="4070 超级画质全开实测：这几款 3A 稳 100+ 帧",
            authorName="帧数狂魔",
            authorAvatarColor="#E0B84A",
            authorAvatarText="帧",
            levelLabel="Lv.11",
            isOfficial=False,
            isFollowing=False,
            publishTime="昨天22:08",
            region="广东",
            circles=["PC游戏", "数码硬件"],
            hotTag="",
            heroMediaKey="fighter",
            heroColor="#2B2B2B",
            caption="统一 1440p + DLSS 质量档，对比无帧生成与有帧生成的体感差异，附设置思路。",
            body=[
                "平台：R5 7600 / 32G 6000 / 4070 Super / 1440p 高刷。驱动用测试当周最新 Game Ready。每款游戏跑内置 benchmark + 实际场景 10 分钟平均。",
                "画质策略：尽量「影视级/超高」，光追能开就开到中高；DLSS 统一质量档。帧生成（FG）单独开关对比。我更关心 1% Low，不只要平均帧好看。",
                "结果概览：几款主流 3A 在不开 FG 时平均多在 90–120，开 FG 后平均轻松上 140+，但 1% Low 提升幅度因游戏而异。强依赖 CPU 的场景，FG 救不了卡顿。",
                "体感上：竞技或不想要延迟的，我个人更愿意关 FG 换更稳的操作；单机过剧情、光追拉满时，FG 很香。显存 12G 在 1440p 基本够用，4K 材质包要小心爆显存。",
                "散热与功耗：双烤机箱温度还行，游戏 GPU 热点比公版略高一截，建议机箱风道别堵。电源我用的 750W 金牌，留余量更安心。",
                "设置口诀：卡平均就降一点体积雾/阴影距离；卡 1% Low 就查后台、查 CPU 占用、关没用的覆盖层。需要某一款的具体选项单可以评论区点名，我补图。",
            ],
            relatedLink="",
            authorNote="测试有误差，仅供同配置参考。别只看平均帧。",
            topicTags=["4070Super", "帧数", "DLSS", "3A"],
            relatedSearch="4070 Super 1440p 帧数",
            collectionName="",
            collectionProgress="",
            likeCount=233,
            starCount=71,
            awardCount=9,
            commentCount=67,
            comments=[
                comment(
                    "r6c1",
                    "帧数狂魔",
                    "#E0B84A",
                    "帧",
                    "Lv.11",
                    "置顶：测试列表和设置截图在图 2–5，图 6 是温度曲线。",
                    "昨天22:12",
                    "广东",
                    31,
                    [
                        reply(
                            "r6c1r1",
                            "显卡等等党",
                            "同 4070S，数据对得上，FG 我只用在单机",
                            "昨天22:40",
                            "浙江",
                        )
                    ],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "r6c2",
                    "CPU瓶颈受害者",
                    "#666666",
                    "C",
                    "Lv.12",
                    "7600 在某几款城里场景确实拖后腿，有同感",
                    "昨天23:05",
                    "北京",
                    22,
                    [
                        reply(
                            "r6c2r1",
                            "帧数狂魔",
                            "对，那种场景关 FG 也救不了，只能等优化或升级",
                            "昨天23:20",
                            "广东",
                            "CPU瓶颈受害者",
                            True,
                        )
                    ],
                ),
                comment(
                    "r6c3",
                    "光追爱好者",
                    "#5B8DEF",
                    "光",
                    "Lv.9",
                    "光追全开 + 质量档 DLSS 是不是你的甜点？",
                    "今天08:18",
                    "上海",
                    14,
                    [
                        reply(
                            "r6c3r1",
                            "帧数狂魔",
                            "1440p 甜点基本是这个，4K 我更倾向平衡档",
                            "今天09:00",
                            "广东",
                            "光追爱好者",
                            True,
                        )
                    ],
                ),
                comment(
                    "r6c4",
                    "电源焦虑",
                    "#FF5A5A",
                    "电",
                    "Lv.6",
                    "650W 行不行啊…",
                    "今天10:30",
                    "河南",
                    6,
                    [
                        reply(
                            "r6c4r1",
                            "帧数狂魔",
                            "看平台和峰值，稳妥还是 750",
                            "今天10:55",
                            "广东",
                            "电源焦虑",
                            True,
                        )
                    ],
                ),
                comment(
                    "r6c5",
                    "笔记本路过",
                    "#888888",
                    "笔",
                    "Lv.4",
                    "笔记本 4070 能对标多少？",
                    "今天11:20",
                    "福建",
                    9,
                    [],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="r7",
            fullTitle="盒友真实：你们是怎么控制买游戏冲动的？",
            authorName="今晚不熬夜",
            authorAvatarColor="#6B7CFF",
            authorAvatarText="夜",
            levelLabel="Lv.6",
            isOfficial=False,
            isFollowing=False,
            publishTime="昨天16:40",
            region="浙江",
            circles=["盒友杂谈", "Steam"],
            hotTag="",
            heroMediaKey="",
            heroColor="#EEF2FF",
            caption="愿望单已经三位数了，每次促销还是忍不住，求靠谱的自制力方法论。",
            body=[
                "认真发问，不是玩梗。我愿望单 130+，库里未玩 40 多。上周末大促又剁了三款，到货（入库）的瞬间很爽，第二天就后悔——因为根本排不上号。",
                "我试过的方法：① 愿望单冷静期 72 小时；② 未玩清到 10 款以内才允许新购；③ 每月娱乐预算锁死；④ 把「想买」写成「为什么现在必须买」。前两条执行得半吊子，第三条最有效，第四条经常被我自己诡辩掉。",
                "更麻烦的是「社交压力」：朋友都在玩、主播都在玩、黑盒热帖都在玩，不买就感觉错过版本答案。理性知道 FOMO，感性还是会点购买。",
                "也有正面例子：去年强制自己把一款 80 小时的 RPG 打完再买新的，体验明显更好，剧情记忆也深。游戏变少之后，单款的快乐密度上升了。",
                "所以想问问盒友：你们有没有真正管用的「止冲动」规则？是预算制、冷静期、还是直接卸载客户端？欢迎晒愿望单数量（一起社死）。",
            ],
            relatedLink="",
            authorNote="评论区别只嘲笑，求方法。",
            topicTags=["愿望单", "剁手", "盒友杂谈", "Steam"],
            relatedSearch="控制买游戏 冲动",
            collectionName="",
            collectionProgress="",
            likeCount=188,
            starCount=42,
            awardCount=4,
            commentCount=95,
            comments=[
                comment(
                    "r7c1",
                    "今晚不熬夜",
                    "#6B7CFF",
                    "夜",
                    "Lv.6",
                    "我先报：愿望单 136，未玩 44。",
                    "昨天16:42",
                    "浙江",
                    12,
                    [],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "r7c2",
                    "未玩羞耻",
                    "#F5C16C",
                    "未",
                    "Lv.18",
                    "规则：未玩 >15 禁止购买。破过两次，都后悔。",
                    "昨天17:10",
                    "广东",
                    41,
                    [
                        reply(
                            "r7c2r1",
                            "今晚不熬夜",
                            "15 这个阈值我可以试试",
                            "昨天17:30",
                            "浙江",
                            "未玩羞耻",
                            True,
                        ),
                        reply("r7c2r2", "库管委员", "我是 >10 就锁，残酷但有效", "昨天18:00", "北京"),
                    ],
                ),
                comment(
                    "r7c3",
                    "预算战士",
                    "#2F9B63",
                    "预",
                    "Lv.11",
                    "每月固定 100，花完下月再说，欲望会自己排队",
                    "昨天18:22",
                    "四川",
                    28,
                    [],
                ),
                comment(
                    "r7c4",
                    "家庭共享信徒",
                    "#5B8DEF",
                    "家",
                    "Lv.9",
                    "和朋友共享库，很多「想玩一下」的其实不用自己买",
                    "昨天19:05",
                    "上海",
                    22,
                    [reply("r7c4r1", "区域党注意", "共享注意地区和 VAC 规则", "昨天19:40", "海外")],
                ),
                comment(
                    "r7c5",
                    "冷静期失败",
                    "#888888",
                    "冷",
                    "Lv.5",
                    "72 小时冷静期结束正好赶上周末，还是买了",
                    "昨天20:18",
                    "江苏",
                    9,
                    [
                        reply(
                            "r7c5r1",
                            "今晚不熬夜",
                            "笑死，同款操作",
                            "昨天20:30",
                            "浙江",
                            "冷静期失败",
                            True,
                        )
                    ],
                ),
                comment(
                    "r7c6",
                    "极简玩家",
                    "#1A1A1A",
                    "极",
                    "Lv.14",
                    "愿望单超过 50 就强制删一批「可能永远不玩」的",
                    "今天08:50",
                    "湖北",
                    17,
                    [],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="f3",
            fullTitle="我哭了",
            authorName="我不吃牛肉讷",
            authorAvatarColor="#B8E0D2",
            authorAvatarText="牛",
            levelLabel="Lv.16",
            isOfficial=False,
            isFollowing=True,
            publishTime="昨天13:31",
            region="江苏",
            circles=["盒友杂谈"],
            hotTag="",
            heroMediaKey="",
            heroColor="#E8D5C4",
            caption="其实我是装的(1> <)☆哈哈哈哈",
            body=[
                "先声明：标题党致歉，但情绪是真的。昨天下午排位连跪，心态直接裂开，坐在电脑前水都顾不上喝，就差把耳机砸了。",
                "冷静下来复盘，其实不是队友的问题（好吧有一丢丢），主要是我自己节奏飘了：开局贪资源，团战技能真空，还爱甩锅。越输越急，越急越丑。",
                "后来我强制自己退出排位，开了一局很久没碰的单机。没有语音没有评分，只有任务和风景。打了两个小时，肩膀松了，也想通了——游戏是来提供反馈的，不是来证明我今天「必须赢」的。",
                "所以标题的「我哭了」有两层：一层是真的破防；一层是破防后发现自己很好笑。发出来给同样倾斜的人：允许自己菜，也允许自己暂停。",
                "今晚准备早睡，排位冷却 24 小时。你们最近有没有因为游戏破防，又被游戏修好的瞬间？",
            ],
            relatedLink="",
            authorNote="评论区友善一点哦，被骂会真哭（不是装的）。",
            topicTags=["破防", "排位", "盒友杂谈", "心态"],
            relatedSearch="游戏心态 连跪",
            collectionName="",
            collectionProgress="",
            likeCount=66,
            starCount=12,
            awardCount=2,
            commentCount=87,
            comments=[
                comment(
                    "f3c1",
                    "我不吃牛肉讷",
                    "#B8E0D2",
                    "牛",
                    "Lv.16",
                    "冷却中，谁劝我上分我拉黑（开玩笑的）。",
                    "昨天13:35",
                    "江苏",
                    9,
                    [],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "f3c2",
                    "连跪战神",
                    "#FF5A5A",
                    "跪",
                    "Lv.10",
                    "太真实了，我都是连跪后切单机回血",
                    "昨天14:02",
                    "广东",
                    26,
                    [
                        reply(
                            "f3c2r1",
                            "我不吃牛肉讷",
                            "单机是心灵牡蛎",
                            "昨天14:20",
                            "江苏",
                            "连跪战神",
                            True,
                        )
                    ],
                ),
                comment(
                    "f3c3",
                    "麦霸队友",
                    "#666666",
                    "麦",
                    "Lv.7",
                    "语音有时候真的会放大焦虑，关麦清净",
                    "昨天15:10",
                    "浙江",
                    14,
                    [],
                ),
                comment(
                    "f3c4",
                    "心态导师",
                    "#5B8DEF",
                    "心",
                    "Lv.20",
                    "建议设置「输两把必休息」，比冷静期好执行",
                    "昨天16:40",
                    "北京",
                    31,
                    [
                        reply(
                            "f3c4r1",
                            "我不吃牛肉讷",
                            "收到，贴显示器上",
                            "昨天17:05",
                            "江苏",
                            "心态导师",
                            True,
                        )
                    ],
                ),
                comment(
                    "f3c5",
                    "装哭识别",
                    "#C9A227",
                    "装",
                    "Lv.8",
                    "看标题以为真哭，进来发现是哲理帖",
                    "昨天18:22",
                    "四川",
                    11,
                    [
                        reply(
                            "f3c5r1",
                            "我不吃牛肉讷",
                            "标题是情绪，内容是复盘hhh",
                            "昨天18:40",
                            "江苏",
                            "装哭识别",
                            True,
                        )
                    ],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="f4",
            fullTitle="微喇裤焊死在身上",
            authorName="我不吃牛肉讷",
            authorAvatarColor="#B8E0D2",
            authorAvatarText="牛",
            levelLabel="Lv.16",
            isOfficial=False,
            isFollowing=True,
            publishTime="2天前",
            region="江苏",
            circles=["盒友杂谈"],
            hotTag="",
            heroMediaKey="",
            heroColor="#3A3A3A",
            caption="yyds微喇裤",
            body=[
                "不是广告，是真香现场。之前一直穿直筒，总觉得微喇是「老气」或者「只有特定身材能穿」。直到双十一随手入了一条基础黑，穿去学校/逛街/甚至网吧开黑，反馈意外地好。",
                "版型重点：微喇不是大喇叭。膝下一点点打开就够了，显腿长的关键是腰线卡对 + 鞋的选择。我配德训和板鞋都还行，配老爹鞋会有点打架。",
                "面料别选太薄的垂感（容易像睡裤），稍微有点结构的更利落。颜色我推黑、深灰、原色牛仔；浅色看打理能力。",
                "码数建议按臀围和大腿，别只看腰围。我第一次拿了常规码，蹲不下去，换了版型偏宽松的就好了。",
                "有人说微喇过时——穿得开心就不过时。你们有没有「一开始嘲讽，穿上就焊死」的单品？评论区聊聊，我继续长草。",
            ],
            relatedLink="",
            authorNote="不接广告，别私信导购链接被骗。",
            topicTags=["穿搭", "微喇", "日常"],
            relatedSearch="微喇裤 搭配",
            collectionName="",
            collectionProgress="",
            likeCount=103,
            starCount=27,
            awardCount=1,
            commentCount=48,
            comments=[
                comment(
                    "f4c1",
                    "我不吃牛肉讷",
                    "#B8E0D2",
                    "牛",
                    "Lv.16",
                    "图是镜子随手拍，画质抱歉，重点看版型。",
                    "2天前",
                    "江苏",
                    8,
                    [],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "f4c2",
                    "直筒忠臣",
                    "#888888",
                    "直",
                    "Lv.9",
                    "被说动了，准备入一条黑的",
                    "2天前",
                    "上海",
                    16,
                    [
                        reply(
                            "f4c2r1",
                            "我不吃牛肉讷",
                            "黑的百搭，先从基础款开始",
                            "2天前",
                            "江苏",
                            "直筒忠臣",
                            True,
                        )
                    ],
                ),
                comment(
                    "f4c3",
                    "鞋控",
                    "#1A1A1A",
                    "鞋",
                    "Lv.12",
                    "德训确实搭，凹凸有致",
                    "昨天09:20",
                    "广东",
                    12,
                    [],
                ),
                comment(
                    "f4c4",
                    "码数灾难",
                    "#FF5A5A",
                    "码",
                    "Lv.6",
                    "我总是买小，蹲下去裂缝的回忆涌上来",
                    "昨天11:05",
                    "湖北",
                    10,
                    [
                        reply(
                            "f4c4r1",
                            "我不吃牛肉讷",
                            "同款阴影，大腿围为王",
                            "昨天11:30",
                            "江苏",
                            "码数灾难",
                            True,
                        )
                    ],
                ),
                comment(
                    "f4c5",
                    "过时警察",
                    "#666666",
                    "过",
                    "Lv.4",
                    "微喇不是又要流行了吗，正好",
                    "昨天15:40",
                    "浙江",
                    7,
                    [],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="f5",
            fullTitle="超级可爱特效(1> <)☆",
            authorName="我不吃牛肉讷",
            authorAvatarColor="#B8E0D2",
            authorAvatarText="牛",
            levelLabel="Lv.16",
            isOfficial=False,
            isFollowing=True,
            publishTime="3天前",
            region="江苏",
            circles=["盒友杂谈", "PC游戏"],
            hotTag="",
            heroMediaKey="",
            heroColor="#F0C8D8",
            caption="去今天爽玩11h千恋万花嘻嘻，睡醒就去健身房～",
            body=[
                "状态汇报：昨天从中午开接到半夜，一共差不多 11 个小时在《千恋＊万花》里度日。不是肝强制，是真的好看又好听，CG 和语音一直在线。",
                "剧情节奏对我很友好：日常甜度拉满的时候会突然给一点情绪冲击，情绪起伏舒服，不会一直腻。路线选择我目前推了一条，准备开二周目补其他。",
                "平台是 PC，全屏+日语语音+中文字幕。第一次玩 gal 的盒友不用慌，系统提示很清楚。记得存档多一点，避免选错要重来一大段。",
                "玩太久的副作用：起来腰是直的但颈椎在抗议，所以今天必须去健身房赎回自己。也提醒大家：甜是真的，久坐也是真的。",
                "有同好的话安利一下你最推的路线（防剧透！用暗号），我二周目参考。以及有没有类似氛围的作品？",
            ],
            relatedLink="",
            authorNote="防剧透警告：评论请折叠关键剧情。",
            topicTags=["千恋万花", "galgame", "二周目"],
            relatedSearch="千恋万花 路线",
            collectionName="",
            collectionProgress="",
            likeCount=91,
            starCount=19,
            awardCount=3,
            commentCount=32,
            comments=[
                comment(
                    "f5c1",
                    "我不吃牛肉讷",
                    "#B8E0D2",
                    "牛",
                    "Lv.16",
                    "健身房打卡回来了，腿软，但精神好。",
                    "3天前",
                    "江苏",
                    6,
                    [],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "f5c2",
                    "和风爱好者",
                    "#F0C8D8",
                    "和",
                    "Lv.13",
                    "11h 很克制了，我第一次直接通宵",
                    "3天前",
                    "上海",
                    18,
                    [
                        reply(
                            "f5c2r1",
                            "我不吃牛肉讷",
                            "不敢通宵，怕第二天人没了",
                            "3天前",
                            "江苏",
                            "和风爱好者",
                            True,
                        )
                    ],
                ),
                comment(
                    "f5c3",
                    "存档狂魔",
                    "#5B8DEF",
                    "存",
                    "Lv.8",
                    "多存档是对的，我有次没存痛失一小时",
                    "昨天10:12",
                    "广东",
                    11,
                    [],
                ),
                comment(
                    "f5c4",
                    "二周目预备",
                    "#C9A227",
                    "二",
                    "Lv.10",
                    "路线暗号：花开的那条，懂的都懂",
                    "昨天14:33",
                    "浙江",
                    14,
                    [
                        reply(
                            "f5c4r1",
                            "我不吃牛肉讷",
                            "收到，列入计划",
                            "昨天15:00",
                            "江苏",
                            "二周目预备",
                            True,
                        )
                    ],
                ),
                comment(
                    "f5c5",
                    "颈椎抗议",
                    "#888888",
                    "颈",
                    "Lv.5",
                    "看完去健身房这波是健康博主行为",
                    "昨天19:20",
                    "北京",
                    9,
                    [],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="f6",
            fullTitle="超大更新！有颜值更有音质！11款超热门音乐播放器+歌词工具汇总！",
            authorName="软件格律诗",
            authorAvatarColor="#F5C16C",
            authorAvatarText="诗",
            levelLabel="Lv.12",
            isOfficial=False,
            isFollowing=True,
            publishTime="昨天19:19",
            region="广东",
            circles=["盒友杂谈", "数码硬件"],
            hotTag="",
            heroMediaKey="",
            heroColor="#1A2A3A",
            caption="一、SPlayer《被惊艳到！给的真的多，一款伟大的音乐播放器！前方多图警告！》",
            body=[
                "这篇是年度整理的大更新版。很多盒友私信问「网易云/QQ 音乐之外还有什么本地播放器」，一并回答。以下软件以 Windows 为主，部分跨平台，下载请走官方或可信源。",
                "一、SPlayer：界面现代，歌词和封面支持好，适合想要「好看又好用」的用户。配置项不少，第一次建议按默认再慢慢改。本地曲库扫描速度在可接受范围。",
                "二、传统强者系：foobar2000 依然是音质党圣杯，可玩性极高，插件生态成熟，但上手门槛也高。AIMP、MusicBee 则在「功能完整 + 相对好上手」之间取得平衡。",
                "三、歌词工具：独立歌词插件/工具适合给老播放器续命，支持桌面歌词、翻译歌词的组合很香。注意歌词源的版权与准确性，错词很影响体验。",
                "四、流媒体+本地混合：有的播放器能挂多音源，适合曲库分散的人。稳定性因版本而异，遇问题先看发行说明。",
                "五、选型建议：只听流媒体 → 官方客户端足够；本地高码率 + 强迫症分类 → foobar/MusicBee；要颜值党 → SPlayer 一类。我的日常是「流媒体一款 + 本地一款」。",
                "评论区可以报你的主力播放器和痛点（占内存、歌词飘、不支持某格式等），我下个版本补坑。图很多，流量预警。",
            ],
            relatedLink="",
            authorNote="不提供破解，不讨论灰色音源。",
            topicTags=["播放器", "软件", "歌词", "本地音乐"],
            relatedSearch="Windows 音乐播放器 推荐",
            collectionName="合集【软件格律诗·工具箱】",
            collectionProgress="18/40",
            likeCount=73,
            starCount=55,
            awardCount=8,
            commentCount=18,
            comments=[
                comment(
                    "f6c1",
                    "软件格律诗",
                    "#F5C16C",
                    "诗",
                    "Lv.12",
                    "置顶：目录在第一张图，可按需跳转。",
                    "昨天19:25",
                    "广东",
                    14,
                    [reply("f6c1r1", "音质老人", "foobar 永远的神", "昨天19:50", "北京")],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "f6c2",
                    "颜值党",
                    "#F0C8D8",
                    "颜",
                    "Lv.7",
                    "SPlayer 界面确实好看，已入坑",
                    "昨天20:10",
                    "上海",
                    11,
                    [],
                ),
                comment(
                    "f6c3",
                    "歌词漂移",
                    "#666666",
                    "词",
                    "Lv.9",
                    "有没有桌面歌词特别稳的方案？",
                    "昨天21:00",
                    "浙江",
                    8,
                    [
                        reply(
                            "f6c3r1",
                            "软件格律诗",
                            "文中歌词工具那节有写，可再看第三部分",
                            "昨天21:20",
                            "广东",
                            "歌词漂移",
                            True,
                        )
                    ],
                ),
                comment(
                    "f6c4",
                    "内存告急",
                    "#FF5A5A",
                    "内",
                    "Lv.5",
                    "8G 内存笔记本求轻量",
                    "昨天22:40",
                    "四川",
                    6,
                    [
                        reply(
                            "f6c4r1",
                            "软件格律诗",
                            "AIMP 或精简配置的 foobar 更合适",
                            "昨天23:00",
                            "广东",
                            "内存告急",
                            True,
                        )
                    ],
                ),
                comment(
                    "f6c5",
                    "收藏党",
                    "#5B8DEF",
                    "藏",
                    "Lv.11",
                    "大更新辛苦了，先赞后看",
                    "今天08:15",
                    "江苏",
                    9,
                    [],
                ),
            ],
        )
    )

    posts.append(
        dict(
            id="f7",
            fullTitle="让人大开眼界！近59.2k星标，一份中国独立开发者项目列表，收藏！",
            authorName="软件格律诗",
            authorAvatarColor="#F5C16C",
            authorAvatarText="诗",
            levelLabel="Lv.12",
            isOfficial=False,
            isFollowing=True,
            publishTime="昨天11:26",
            region="广东",
            circles=["盒友杂谈"],
            hotTag="",
            heroMediaKey="",
            heroColor="#E8F0F5",
            caption="如果你关注科技圈、软件产品或者独立开发领域，应该经常会遇到一个问题：国内到底有哪些个人开发者正在做自己的产品？",
            body=[
                "这份列表在 GitHub 上长期维护，星标已经来到约 59.2k，内容是「中国独立开发者/团队做出的产品与项目」索引。它不是排行榜，更像地图：让你知道有人在默默做很酷的事。",
                "列表通常按领域划分：效率工具、设计、开发者工具、AI 应用、生活类等等。点进去能看到项目简介和主页。对我这种喜欢「找替代方案」的人非常友好——很多小而美的产品官方商店不一定推得到。",
                "使用建议：① 先收藏再翻，避免看完就忘；② 关注更新日志，独立开发迭代快；③ 给真正在用的项目反馈/赞助，比白嫖 star 更有用；④ 注意协议与隐私，小项目也要看清楚数据是否上传。",
                "对想做独立开发的人：这份列表也是心态药。你会发现成功不是只有独角兽一种形状，有人靠订阅活得很好，有人靠开源建立影响力。",
                "我自己从里面挖到过两款效率工具，现在还在主力使用。你们有没有「从小列表挖到宝藏」的经历？欢迎在评论区安利（附一句话用途）。",
            ],
            relatedLink="GitHub 中国独立开发者项目列表（请自行搜索最新仓库）",
            authorNote="星标数会变，以仓库页面为准。",
            topicTags=["独立开发", "GitHub", "工具", "开源"],
            relatedSearch="中国独立开发者 列表",
            collectionName="合集【软件格律诗·工具箱】",
            collectionProgress="19/40",
            likeCount=32,
            starCount=28,
            awardCount=5,
            commentCount=3,
            comments=[
                comment(
                    "f7c1",
                    "软件格律诗",
                    "#F5C16C",
                    "诗",
                    "Lv.12",
                    "欢迎补充你们知道但列表可能没收录的项目。",
                    "昨天11:30",
                    "广东",
                    4,
                    [],
                    pinned=True,
                    is_author=True,
                ),
                comment(
                    "f7c2",
                    "开源巡游",
                    "#2F9B63",
                    "开",
                    "Lv.14",
                    "这列表我 star 过，定期会翻，像逛集市",
                    "昨天12:10",
                    "北京",
                    9,
                    [
                        reply(
                            "f7c2r1",
                            "软件格律诗",
                            "集市这个比喻太准了",
                            "昨天12:40",
                            "广东",
                            "开源巡游",
                            True,
                        )
                    ],
                ),
                comment(
                    "f7c3",
                    "独立开发萌新",
                    "#6B7CFF",
                    "萌",
                    "Lv.3",
                    "看完更想动手做自己的工具了",
                    "昨天15:20",
                    "杭州",
                    6,
                    [],
                ),
            ],
        )
    )

    return posts


def main():
    posts = build_posts()
    fragment = ",\n".join(detail(p) for p in posts)
    out = Path(r"E:\apps\deveco\BlackBox\Home\mock_raw\_missing_details.ets")
    out.write_text(fragment + "\n", encoding="utf-8")
    print("wrote", out, "chars", len(fragment), "ids", [p["id"] for p in posts])

    model = Path(r"E:\apps\deveco\BlackBox\Home\src\main\ets\model\HomeModel.ets")
    text = model.read_text(encoding="utf-8")
    marker = "\n];\n\nexport function getPostDetailById"
    idx = text.find(marker)
    if idx < 0:
        raise SystemExit("marker not found")
    before = text[:idx]
    if not before.rstrip().endswith("}"):
        raise SystemExit("unexpected end: " + repr(before[-80:]))
    new_text = before + ",\n" + fragment + text[idx:]
    model.write_text(new_text, encoding="utf-8")
    print("injected, new lines", new_text.count("\n") + 1)

    import re

    detail_main = re.findall(r"\{\s*id:\s*'([^']+)',\s*fullTitle:", new_text)
    missing = ["r4", "r5", "r6", "r7", "f3", "f4", "f5", "f6", "f7"]
    print("all present", all(m in detail_main for m in missing))
    print("detail count", len(detail_main))


if __name__ == "__main__":
    main()
